services:
  rabbit:
    image: rabbitmq:4-management
    restart: always
    hostname: rabbitmqhost
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbit_volume:
