services:
  postgres_db:
    image: postgres:17
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - "local_postgres_volume:/var/lib/postgresql/data"
    networks:
      - bridge-network

volumes:
  local_postgres_volume:

networks:
  bridge-network:
    driver: bridge
