services:
  mongo-db:
    image: mongo:8
    restart: always
    # without credentials in order to simplify connection strings
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - bridge-network
    volumes:
      - local_mongo_volume:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    networks:
      - bridge-network
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-db:27017
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "pass"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

volumes:
  local_mongo_volume:

networks:
  bridge-network:
    driver: bridge
